FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["CarRental.sln", "./"]
COPY ["src/CarRental.csproj", "src/"]
COPY ["tests/WebApiTests/WebApiTests.csproj", "tests/WebApiTests/"]

RUN dotnet restore

COPY . .

ENTRYPOINT ["dotnet", "test", "tests/WebApiTests/WebApiTests.csproj"]